version: '3.8'

services:
  # Конфигурация для PG_BOOKS
  postgres_books:
    image: postgres:latest
    container_name: "postgres_books"
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5630:5432"
    volumes:
      - ./conf/postgres_a:/scripts
      - ./conf/postgres_a_vol:/var/lib/postgresql/data/pgdata
      #- ./init-users-shard1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

  # Конфигурация для PG_BOOKS_1
  postgres_books1:
    image: postgres:latest
    container_name: "postgres_books1"
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5631:5432"
    volumes:
      - ./conf/postgres_a1:/scripts
      - ./conf/postgres_a1_vol:/var/lib/postgresql/data/pgdata
      #- ./init-users-shard1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

  # Конфигурация для PG_BOOKS_2
  postgres_books2:
    image: postgres:latest
    container_name: "postgres_books2"
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5632:5432"
    volumes:
      - ./conf/postgres_a2:/scripts
      - ./conf/postgres_a2_vol:/var/lib/postgresql/data/pgdata
      #- ./init-users-shard1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

  # Конфигурация для PG_BOOKS_3
  postgres_books3:
    image: postgres:latest
    container_name: "postgres_books3"
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5633:5432"
    volumes:
      - ./conf/postgres_a3:/scripts
      - ./conf/postgres_a3_vol:/var/lib/postgresql/data/pgdata
      #- ./init-users-shard1.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local